# https://github.com/bbatsov/ruby-style-guide

AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

# Comments don't need to be in English only
Style/AsciiComments:
  Enabled: false

# Default 80
Metrics/LineLength:
  Max: 120

# Default 10
Metrics/MethodLength:
  Max: 20
